name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: list assignment test
      id: list-assignment-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: list assignment test
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LIST-ASSIGNMENT-TEST_RESULTS: "${{steps.list-assignment-test.outputs.result}}"
      with:
        runners: list-assignment-test
